id: IF45A6558
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:11:45.633124
last_modified: 2023-02-08 15:11:45.633229
source_metadata:
  title: Maitreyavyākaraṇa
  language: sa
bases:
  DEA3:
    base_file: DEA3.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
